using Api.Models;
using Azure;
using Azure.AI.OpenAI;

namespace Api.services
{
    public class IncidentAnalysisService
    {
        private readonly IConfiguration _configuration;

        public IncidentAnalysisService(IConfiguration configuration)
        {
            _configuration = configuration;
        }
        public async Task<IncidentAnalysisResponse> Analyze(
        IncidentAnalysisRequest request)
        {
            var endpoint =
                _configuration["AZURE_OPENAI_ENDPOINT"];

            var key =
                _configuration["AZURE_OPENAI_API_KEY"];

            var deployment =
                _configuration["AZURE_OPENAI_DEPLOYMENT"];

            var client = new AzureOpenAIClient(
                new Uri(endpoint),
                new AzureKeyCredential(key));

            var chatClient =
                client.GetChatClient(deployment);

            var prompt = $@"
                Analyze this production incident.

                Error:
                {request.Error}

                Logs:
                {request.Logs}

                Return:
                1. Severity
                2. Root Cause
                3. Recommendation
                ";

            var response =
                await chatClient.CompleteChatAsync(prompt);

            string result =
                response.Value.Content[0].Text;

            return new IncidentAnalysisResponse
            {
                Severity = "AI Generated",
                RootCause = result,
                Recommendation = "Generated by Azure OpenAI"
            };
        }
    }
}
