@Api_HostAddress = http://localhost:5065

### Get all products (normal)
GET {{Api_HostAddress}}/api/products
Accept: application/json

### Get one product by id (normal)
GET {{Api_HostAddress}}/api/products/1
Accept: application/json

### Get one product - SLOW lever (5s delay)
GET {{Api_HostAddress}}/api/products/1?slow=true
Accept: application/json

### Get one product - CRASH lever (throws 500)
GET {{Api_HostAddress}}/api/products/1?crash=true
Accept: application/json

### Create an order (memory leak lever)
POST {{Api_HostAddress}}/api/orders
Content-Type: application/json

{
  "productId": 1,
  "quantity": 2
}

###
