name: Build ASP.NET API

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore Api/Api.csproj

    - name: Build Project
      run: dotnet build Api/Api.csproj --configuration Release --no-restore

    - name: Publish Project
      run: dotnet publish Api/Api.csproj --configuration Release --output ./publish
